//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartyHard.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterClasses
    {
        public MasterClasses()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int Id { get; set; }
        public string MasterClassName { get; set; }
        public string Descriptions { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
