//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartyHard.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int EventTypeId { get; set; }
        public int ServiceId { get; set; }
        public int MasterClassId { get; set; }
        public int UserId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Address { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual EventTypes EventTypes { get; set; }
        public virtual MasterClasses MasterClasses { get; set; }
        public virtual Services Services { get; set; }
        public virtual Users Users { get; set; }
    }
}
